name: toshl-fixer
channels:
  - conda-forge
dependencies:
  - python=3.8.*
  - pip=20.1.1
  - click=7.0
  - pandas=0.25.3
  - python-dotenv=0.10.3
  - flask=1.1.1
  - gunicorn=20.0.4
  - nomkl
  - pip:
      - "git+https://github.com/noamelf/toshl-python.git@master#egg=toshl"
      - prompt-toolkit==2.0.10
